#!/usr/bin/python3
import sys
import os
import json

args = sys.argv[1:-1]  # -1 to chop off dummy-arg
args_body = json.dumps(args)[1:-1]

bindir = os.getenv("BINDIR")
assert bindir is not None

sys.stdout.write(f"// Auto-generated by beam_arg_swiper.py\n\n")

sys.stdout.write(f"#define BINDIR {json.dumps(bindir)}\n\n")

sys.stdout.write(f"const int beam_argc = {len(args)};\n")
sys.stdout.write(f"const char *beam_argv[] = {{ {args_body} }};\n")  # NOTE: not null terminated, will append argv[1:] onto this